# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "wPK32UWCdpR6IJId4Ck04nmnmb+RNh6CWNvNKkqJ1C+E/i4Vwvfihi3Em3bNQh/Wf0bWztXwotmwFcBiwNJVbBQ56RUIm2Fixbi+rAlE7jgqe5f0Upp8E4pGykgyhWnqhfOMVhlESc3jRY3uAfF6nO36jPaS85Bzh5gngx9exkryd/qfzXfleiOEhzuUlDaEtHnFwskgInECnmxZ/aCzVt0bFKk86nKJm5aQVeovkN2a2GC7/+y+pDZyEc7FyI8MSz6nYNShL2U1Gy95sncXZ23HKslZ50pzw+IpmAPv/S38aRELSBKAcw+Try8PGvsb3yr/zT4hev9lmgGeAKRLkD8RWEpG8w2jH4SJZUnWJN6rPvfrJZlz/FeMNmyp8ADLAGfO23zugv6ZfaExosmQSQDTNvTLkACv1EtI+ENyTG6BoTYPaoUZmcFlPkvsNNjKoVYyNko+R0S1+3CgEIQRi6jjTasuj6foCf8clHr9GH3Ja536VgdgedfoqNchidhAmS1QjbC8mf+xFDpEOJKRT90iPZL+vhVIXaOwyZJK+zvAOe+LpsRtyuNxx8G7BjzDI7Abuy0HxnA648SU2iT2BJeM9VOPe8WkUrG54167BJhh9HFWAKcOwaU5iPYVZ/zq3b6bp25eLT8VltFAP57trbomuL82mWIEK1MckWRrtSA="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
