travis:
  secure:
    BINSTAR_TOKEN: wPK32UWCdpR6IJId4Ck04nmnmb+RNh6CWNvNKkqJ1C+E/i4Vwvfihi3Em3bNQh/Wf0bWztXwotmwFcBiwNJVbBQ56RUIm2Fixbi+rAlE7jgqe5f0Upp8E4pGykgyhWnqhfOMVhlESc3jRY3uAfF6nO36jPaS85Bzh5gngx9exkryd/qfzXfleiOEhzuUlDaEtHnFwskgInECnmxZ/aCzVt0bFKk86nKJm5aQVeovkN2a2GC7/+y+pDZyEc7FyI8MSz6nYNShL2U1Gy95sncXZ23HKslZ50pzw+IpmAPv/S38aRELSBKAcw+Try8PGvsb3yr/zT4hev9lmgGeAKRLkD8RWEpG8w2jH4SJZUnWJN6rPvfrJZlz/FeMNmyp8ADLAGfO23zugv6ZfaExosmQSQDTNvTLkACv1EtI+ENyTG6BoTYPaoUZmcFlPkvsNNjKoVYyNko+R0S1+3CgEIQRi6jjTasuj6foCf8clHr9GH3Ja536VgdgedfoqNchidhAmS1QjbC8mf+xFDpEOJKRT90iPZL+vhVIXaOwyZJK+zvAOe+LpsRtyuNxx8G7BjzDI7Abuy0HxnA648SU2iT2BJeM9VOPe8WkUrG54167BJhh9HFWAKcOwaU5iPYVZ/zq3b6bp25eLT8VltFAP57trbomuL82mWIEK1MckWRrtSA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
